# Generated by Django 4.2 on 2024-09-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
