# Generated by Django 4.2 on 2024-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
