# Generated by Django 4.2 on 2024-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailmessage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-sent_date']},
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='recieved_date',
            new_name='received_date',
        ),
    ]
